# Generated by Django 2.0.7 on 2018-07-25 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20180725_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markettable1',
            name='date',
        ),
        migrations.RemoveField(
            model_name='markettable2',
            name='date',
        ),
        migrations.RemoveField(
            model_name='markettable3',
            name='date',
        ),
        migrations.RemoveField(
            model_name='markettable4',
            name='date',
        ),
        migrations.RemoveField(
            model_name='markettable5',
            name='date',
        ),
        migrations.RemoveField(
            model_name='markettable6',
            name='date',
        ),
    ]
